CREATE TABLE "users" (
  "id" serial PRIMARY KEY NOT NULL,
  "username" VARCHAR ( 255 ) UNIQUE NOT NULL,
  "email" VARCHAR ( 255 ) UNIQUE NOT NULL,
  "hashed_password" VARCHAR ( 255 ) NOT NULL
);

CREATE TABLE "jobs" (
  "id" serial PRIMARY KEY NOT NULL,
  "check_number" VARCHAR(255),
  "priority" VARCHAR(255),
  "description" VARCHAR(255),
  "tech_notes" VARCHAR(255),
  "completion_notes" VARCHAR(255),
  "duration" INTEGER,
  "time_frame_promised_start" VARCHAR(255),
  "time_frame_promised_end" VARCHAR(255),
  "start_date" TIMESTAMP,
  "end_date" TIMESTAMP,
  "customer_name" VARCHAR(255),
  "status" VARCHAR(255),
  "contact_first_name" VARCHAR(255),
  "contact_last_name" VARCHAR(255),
  "street_1" VARCHAR(255),
  "street_2" VARCHAR(255),
  "city" VARCHAR(255),
  "state_prov" VARCHAR(255),
  "postal_code" VARCHAR(255),
  "location_name" VARCHAR(255),
  "is_gated" BOOLEAN,
  "gate_instructions" VARCHAR(255),
  "category" VARCHAR(255),
  "source" VARCHAR(255),
  "payment_type" VARCHAR(255),
  "customer_payment_terms" VARCHAR(255),
  "project" VARCHAR(255),
  "phase" VARCHAR(255),
  "po_number" VARCHAR(255),
  "contract" VARCHAR(255),
  "note_to_customer" VARCHAR(255),
  "called_in_by" VARCHAR(255),
  "is_requires_follow_up" BOOLEAN,
  "agents" JSON,
  "custom_fields" JSON,
  "equipment" JSON,
  "techs_assigned" JSON,
  "tasks" JSON,
  "notes" JSON,
  "products" JSON,
  "services" JSON,
  "other_charges" JSON,
  "labor_charges" JSON,
  "expenses" JSON
);

CREATE TABLE "customers" (
  "id" serial PRIMARY KEY NOT NULL,
  "customer_name" VARCHAR(255),
  "parent_customer" VARCHAR(255),
  "account_number" VARCHAR(255),
  "private_notes" VARCHAR(255),
  "public_notes" VARCHAR(255),
  "credit_rating" VARCHAR(255),
  "labor_charge_type" VARCHAR(255),
  "labor_charge_default_rate" DECIMAL,
  "last_serviced_date" TIMESTAMP,
  "is_bill_for_drive_time" BOOLEAN,
  "is_vip" BOOLEAN,
  "referral_source" VARCHAR(255),
  "agent" VARCHAR(255),
  "discount" DECIMAL,
  "discount_type" VARCHAR(255),
  "payment_type" VARCHAR(255),
  "payment_terms" VARCHAR(255),
  "assigned_contract" VARCHAR(255),
  "industry" VARCHAR(255),
  "is_taxable" BOOLEAN,
  "tax_item_name" VARCHAR(255),
  "qbo_sync_token" INTEGER,
  "qbo_currency" VARCHAR(255),
  "contacts" JSON,
  "locations" JSON,
  "custom_fields" JSON
);
